services:
  db:
    image: mysql
    env_file: ./backend/env/mysqldb.env
    volumes:
      - data:/var/lib/mysql
    container_name: mysqldb
    ports:
      - "3307:3306"

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/env/backend.env
    container_name: simpletodo-backend
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    volumes:
    - ./frontend/src:/app/src
    container_name: simpletodo-frontend
    ports:
      - "5173:5173"
    depends_on: 
      - backend

volumes:
  data: